name: MacOS C/C++ CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
      env: 
        SUBTARGET: tiny
        MAME: mametiny64
    - name: make check
      run: make check
      env: 
        SUBTARGET: tiny
        MAME: mametiny64
    - name: make distcheck
      run: make distcheck
      env: 
        SUBTARGET: tiny
        MAME: mametiny64
