name: MacOS C/C++ CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        brew update
        brew install asio flac glm jpeg lua pkg-config portaudio portmidi pugixml rapidjson sdl2 sdl2_ttf sphinx-doc sqlite utf8proc
        export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib"
    - name: Make
      run: make
    - name: Upload CHDMAN
      uses: actions/upload-artifact@v1.0.0
      with:
        name: chdman
        path: ./build/osx_clang/bin/x64/Release/chdman
