name: MacOS C/C++ CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      env:
        SUBTARGET: chdman
        SOURCES: src/tools/chdman.cpp
      run:
        brew install sdl2
        gmake

